[project]
name = "mlputils"
description = "tools to train and test machine learning potentials"
readme = "README.md"
authors = [{name="Gilberto Nardi", email="gilberto.nardi@unimi.it"}]
version = "0.1.0"

dependencies = [
  "ase",
  "numpy",
  "pyyaml",
  "scipy"
]

[project.optional-dependencies]
flare = ["mir-flare"]
mace = ["mace"]
phonopy = ["phonopy"]
snow = ["snow"]
all = [
  "mir-flare",
  "mace",
  "phonopy",
  "snow",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["mlputils*"]
exclude = ["workflows_examples*"]
