[project]
name = "mlputils"
description = "tools to train and test machine learning potentials"
readme = "README.md"
authors = [{name="Gilberto Nardi", email="gilberto.nardi@unimi.it"}]
dynamic = ["version"]

dependencies = [
  "ase",
  "numpy",
  "pyyaml",
  "scipy"
]

[project.optional-dependencies]
extras = [
  "phonopy",
  "mir-flare",
  "mace"
]

[project.scripts]
benchmark = "mlputils.benchmark:cli"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["mlputils*"]
exclude = ["workflows_examples*"]
